# Generated by Django 3.1 on 2020-09-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythicPlusScore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCharacterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('realm', models.CharField(max_length=50)),
                ('server', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CharacterInfo',
        ),
    ]
